name: Test

on: [ push ]

permissions:
  contents: read

jobs:

  test-81:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: xdebug
      - uses: actions/checkout@v3
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php81-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-81
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run tests
        run: composer run-script test -- --coverage-clover .cache/clover.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: .cache/clover.xml

  test-82:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: xdebug
      - uses: actions/checkout@v3
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php82-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-82
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run tests
        run: composer run-script test -- --coverage-clover .cache/clover.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: .cache/clover.xml
